#!/bin/sh
# Schaltet die Ansicht einer tmux-Session weiter:
#   nebeneinander (even-horizontal) -> Raster (tiled) -> Tabs (je ein Fenster)
#
# Aufruf mit einer Fenster-ID als Argument (aus tmux heraus: "#{window_id}").
# Ohne Argument -- etwa aus einer Compositor-Taste heraus -- wird das Fenster
# des zuletzt aktiven angehaengten Clients genommen.
#
# Jedes tmux-Kommando bekommt ein explizites -t. Ohne Ziel greifen sie auf die
# zuletzt benutzte Session zu, nicht auf die gemeinte: dann raeumt der Zyklus
# eine fremde Session leer.
set -eu

win=${1:-}
if [ -z "$win" ]; then
    # Die Session des zuletzt aktiven angehaengten Clients -- das ist die,
    # die der User gerade ansieht. Weder "display -p" ohne Ziel noch
    # "display -p -c <client>" taugen dafuer: beide liefern die zuletzt
    # benutzte Session, -c waehlt nur das Ausgabeziel. Also ueber
    # #{client_session} gehen und das als -t setzen.
    sess=$(tmux list-clients -F '#{client_activity} #{client_session}' 2>/dev/null |
           sort -n | tail -n 1 | cut -d' ' -f2-)
    [ -n "$sess" ] || exit 0
    win=$(tmux display-message -p -t "$sess" '#{window_id}')
fi

# Mehr als ein Fenster heisst Tab-Modus, egal was zuletzt gemerkt wurde --
# der User kann jederzeit von Hand Fenster aufmachen.
windows=$(tmux list-windows -t "$win" -F x | wc -l)
mode=$(tmux show-options -qv -t "$win" @viewmode || true)
[ "$windows" -gt 1 ] && mode=tabs

gather() {
    tmux list-windows -t "$win" -F '#{window_id}' | grep -vx "$win" | while read -r w; do
        tmux join-pane -s "$w" -t "$win"
        # Nach jedem Schritt neu anordnen, sonst geht ab ein paar Fenstern
        # der Platz fuer den naechsten Pane aus.
        tmux select-layout -t "$win" even-horizontal
    done
}

case "$mode" in
    horizontal)
        gather
        tmux select-layout -t "$win" tiled
        new=tiled
        ;;
    tiled)
        tmux list-panes -t "$win" -F '#{pane_id}' | tail -n +2 | while read -r p; do
            tmux break-pane -d -a -s "$p" -t "$win"
        done
        new=tabs
        ;;
    *)
        gather
        tmux select-layout -t "$win" even-horizontal
        new=horizontal
        ;;
esac

tmux set-option -t "$win" @viewmode "$new"
tmux display-message -t "$win" "Ansicht: $new"
