# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs


# Added by Antigravity CLI installer
export PATH="/home/michi/.local/bin:$PATH"
. "$HOME/.cargo/env"

# Claude Code auf tty1 automatisch starten
[ -f ~/.config/tty-claude.sh ] && . ~/.config/tty-claude.sh
